/**
 * Job Summary service for generating GitHub Actions Job Summaries
 */

import * as core from "@actions/core";
import { AnalysisResult, AnalysisOptions } from "../types/index.js";
import { generateAnalysisContent, RepositoryContext } from "../utils/markdown-utils.js";

/**
 * Generate complete job summary
 */
function generateJobSummary(
  results: AnalysisResult[],
  config: AnalysisOptions,
  eventType: string,
  context: RepositoryContext,
): string {
  const logoUrl =
    "https://raw.githubusercontent.com/markupai/content-guardian-action/refs/heads/main/icons/markup_ai_mark_logo.svg";
  const header = `# 🔍 Analysis Results <img src="${logoUrl}" alt="Markup AI" width="20" height="20" align="right" />

This summary was automatically generated by the Markup AI GitHub Action for **${eventType}** event.`;

  return generateAnalysisContent(results, config, header, eventType, context);
}

/**
 * Create and write job summary to GitHub Actions
 */
export async function createJobSummary(
  results: AnalysisResult[],
  config: AnalysisOptions,
  eventType: string,
  context: RepositoryContext,
): Promise<void> {
  try {
    if (results.length === 0) {
      await core.summary
        .addHeading("🔍 Analysis Results")
        .addRaw("No files were analyzed.")
        .write();
      return;
    }

    const summaryContent = generateJobSummary(results, config, eventType, context);

    await core.summary.addRaw(summaryContent).write();

    core.info("✅ Job summary created successfully");
  } catch (error) {
    core.error(`Failed to create job summary: ${String(error)}`);
  }
}
