/**
 * Job Summary service for generating GitHub Actions Job Summaries
 */

import * as core from "@actions/core";
import { AnalysisOptions, AnalysisResult } from "../types/index.js";
import { generateAnalysisContent, RepositoryContext } from "../utils/markdown-utils.js";

function generateJobSummary(
  results: AnalysisResult[],
  options: AnalysisOptions,
  eventType: string,
  context: RepositoryContext,
): string {
  const header = `# 🔍 Markup AI Analysis Results

This summary was automatically generated by the Markup AI GitHub Action for **${eventType}** event.`;

  return generateAnalysisContent(results, options, header, eventType, context);
}

export async function createJobSummary(
  results: AnalysisResult[],
  options: AnalysisOptions,
  eventType: string,
  context: RepositoryContext,
): Promise<void> {
  try {
    if (results.length === 0) {
      await core.summary
        .addHeading("🔍 Analysis Results")
        .addRaw("No files were analyzed.")
        .write();
      return;
    }

    const summaryContent = generateJobSummary(results, options, eventType, context);
    await core.summary.addRaw(summaryContent).write();
    core.info("✅ Job summary created successfully");
  } catch (error) {
    core.error(`Failed to create job summary: ${String(error)}`);
  }
}
