/**
 * PR Comment service for managing comments on pull requests
 *
 * Both the summary issue comment and the inline review comments are tagged
 * with a hidden HTML marker (rendered invisibly in GitHub's markdown). On
 * each run we reconcile our existing tagged comments against the freshly
 * computed set:
 *
 *  - new (path, line) → create
 *  - same (path, line), different body → update in place
 *  - existing (path, line) not in the new set → delete (the issue was fixed
 *    or the affected line was removed from the diff)
 *
 * The marker is the deduplication / ownership boundary; comments without it
 * are treated as foreign and left untouched, except as a back-compat fallback
 * for the very first run after this code lands (see findExistingComment).
 */

import * as core from "@actions/core";
import * as github from "@actions/github";
import { AnalysisIssue, AnalysisOptions, AnalysisResult } from "../types/index.js";
import { generateAnalysisContent, RepositoryContext } from "../utils/markdown-utils.js";
import { capitalizeLabel, truncateText, wrapInlineCode } from "../utils/string-utils.js";
import { handleGitHubError, logError } from "../utils/error-utils.js";

export interface PRCommentData {
  owner: string;
  repo: string;
  prNumber: number;
  results: AnalysisResult[];
  options: AnalysisOptions;
  eventType: string;
}

interface ReviewCommentPayload {
  path: string;
  line: number;
  side: "RIGHT";
  body: string;
}

interface ExistingReviewComment {
  id: number;
  path: string;
  line: number;
  body: string;
}

export interface ReviewCommentReconcileResult {
  toCreate: ReviewCommentPayload[];
  toUpdate: { id: number; body: string }[];
  toDelete: number[];
}

const MAX_REVIEW_COMMENTS = 50;
const MAX_ISSUES_PER_COMMENT = 5;
const MAX_ORIGINAL_LENGTH = 160;

/** Hidden HTML markers used to identify comments owned by this action. */
const SUMMARY_MARKER = "<!-- markup-ai-action:summary -->";
const REVIEW_MARKER = "<!-- markup-ai-action:review -->";

/** Back-compat: comments created before markers were introduced are still
 * findable via a substring match on the rendered header text. Used only
 * once per PR, then replaced with a properly-marked body. */
const LEGACY_SUMMARY_HEADER = "Markup AI Analysis Results";

function lineKey(path: string, line: number): string {
  return `${path}:${line.toString()}`;
}

function generateCommentBody(
  results: AnalysisResult[],
  options: AnalysisOptions,
  eventType: string,
  context: RepositoryContext,
): string {
  const header = `${SUMMARY_MARKER}
## 🔍 Markup AI Analysis Results

This comment was automatically generated by the Markup AI GitHub Action for **${eventType}** event.`;

  return generateAnalysisContent(results, options, header, eventType, context);
}

function pickSuggestion(issue: AnalysisIssue["issue"]): string | null {
  if (issue.suggestion && issue.suggestion.length > 0) return issue.suggestion;
  if (issue.suggestions && issue.suggestions.length > 0) return issue.suggestions[0];
  return null;
}

function applyInlineSuggestion(
  issue: AnalysisIssue["issue"],
  lineText: string,
  column: number,
): string | null {
  const suggestion = pickSuggestion(issue);
  const original = issue.position?.text ?? issue.context_surface ?? "";
  if (!suggestion || !original || !lineText) return null;

  const columnIndex = Math.min(Math.max(column, 0), lineText.length);
  const after = lineText.slice(columnIndex);
  if (after.startsWith(original)) {
    return `${lineText.slice(0, columnIndex)}${suggestion}${after.slice(original.length)}`;
  }

  const fallbackIndex = lineText.indexOf(original);
  if (fallbackIndex >= 0) {
    return `${lineText.slice(0, fallbackIndex)}${suggestion}${lineText.slice(
      fallbackIndex + original.length,
    )}`;
  }
  return null;
}

function buildReviewCommentBody(issues: AnalysisIssue[]): string {
  const lines = issues.slice(0, MAX_ISSUES_PER_COMMENT).map(({ issue, lineText, column }) => {
    const category = capitalizeLabel(issue.category);
    const guideline = issue.guideline_name ? capitalizeLabel(issue.guideline_name) : "";
    const heading = guideline ? `${category} / ${guideline}` : category;
    const original = truncateText(
      issue.position?.text ?? issue.context_surface ?? "",
      MAX_ORIGINAL_LENGTH,
    );
    const suggestion = pickSuggestion(issue);
    const explanationLine = issue.explanation ? `\n*Explanation: ${issue.explanation}*` : "";
    const inline = applyInlineSuggestion(issue, lineText, column);

    let suggestionBlock = "";
    if (inline) {
      suggestionBlock = `${explanationLine}\n\`\`\`suggestion\n${inline}\n\`\`\``;
    } else if (suggestion) {
      suggestionBlock = `${explanationLine}\nSuggestion: ${wrapInlineCode(truncateText(suggestion, MAX_ORIGINAL_LENGTH))}`;
    } else if (issue.explanation) {
      suggestionBlock = explanationLine;
    }

    const severity = ` (Severity: ${capitalizeLabel(issue.severity)})`;
    return `- **${heading}${severity}**: ${wrapInlineCode(original || "(no excerpt)")}${suggestionBlock}`;
  });

  const moreCount = issues.length - lines.length;
  if (moreCount > 0) {
    lines.push(`- _${moreCount.toString()} more issue(s) on this line_`);
  }

  return `${REVIEW_MARKER}\n**Markup AI** detected issues:\n${lines.join("\n")}`;
}

function buildReviewComments(results: AnalysisResult[]): ReviewCommentPayload[] {
  const grouped = new Map<string, { path: string; line: number; issues: AnalysisIssue[] }>();

  for (const result of results) {
    for (const issue of result.issues) {
      if (!issue.line || issue.line <= 0) continue;
      const key = lineKey(result.filePath, issue.line);
      const existing = grouped.get(key);
      if (existing) {
        existing.issues.push(issue);
      } else {
        grouped.set(key, { path: result.filePath, line: issue.line, issues: [issue] });
      }
    }
  }

  const comments: ReviewCommentPayload[] = [];
  for (const { path, line, issues } of grouped.values()) {
    if (comments.length >= MAX_REVIEW_COMMENTS) break;
    comments.push({
      path,
      line,
      side: "RIGHT",
      body: buildReviewCommentBody(issues),
    });
  }

  return comments;
}

/**
 * Pure function: given the existing tagged review comments and the desired
 * comments for this run, partition into the three API actions.
 *
 * - toCreate: desired (path,line) with no existing match
 * - toUpdate: same (path,line) but body differs
 * - toDelete: existing (path,line) with no desired match
 *
 * Identical bodies at the same (path,line) are intentionally omitted (no-op).
 */
export function reconcileReviewComments(
  existing: ExistingReviewComment[],
  desired: ReviewCommentPayload[],
): ReviewCommentReconcileResult {
  const existingByKey = new Map<string, ExistingReviewComment>();
  for (const e of existing) existingByKey.set(lineKey(e.path, e.line), e);

  const desiredByKey = new Map<string, ReviewCommentPayload>();
  for (const d of desired) desiredByKey.set(lineKey(d.path, d.line), d);

  const toCreate: ReviewCommentPayload[] = [];
  const toUpdate: { id: number; body: string }[] = [];
  const toDelete: number[] = [];

  for (const [key, d] of desiredByKey) {
    const e = existingByKey.get(key);
    if (!e) {
      toCreate.push(d);
    } else if (e.body !== d.body) {
      toUpdate.push({ id: e.id, body: d.body });
    }
  }

  for (const [key, e] of existingByKey) {
    if (!desiredByKey.has(key)) {
      toDelete.push(e.id);
    }
  }

  return { toCreate, toUpdate, toDelete };
}

async function listAllReviewComments(
  octokit: ReturnType<typeof github.getOctokit>,
  owner: string,
  repo: string,
  prNumber: number,
): Promise<ExistingReviewComment[]> {
  try {
    const comments =
      typeof octokit.paginate === "function"
        ? await octokit.paginate(octokit.rest.pulls.listReviewComments, {
            owner,
            repo,
            pull_number: prNumber,
            per_page: 100,
          })
        : (
            await octokit.rest.pulls.listReviewComments({
              owner,
              repo,
              pull_number: prNumber,
              per_page: 100,
            })
          ).data;

    const ours: ExistingReviewComment[] = [];
    for (const c of comments) {
      if (!c.body || !c.body.includes(REVIEW_MARKER)) continue;
      if (!c.path || typeof c.line !== "number") continue;
      ours.push({ id: c.id, path: c.path, line: c.line, body: c.body });
    }
    return ours;
  } catch (error) {
    core.warning(`Failed to load existing review comments: ${String(error)}`);
    return [];
  }
}

async function findExistingComment(
  octokit: ReturnType<typeof github.getOctokit>,
  owner: string,
  repo: string,
  prNumber: number,
): Promise<number | null> {
  try {
    const comments =
      typeof octokit.paginate === "function"
        ? await octokit.paginate(octokit.rest.issues.listComments, {
            owner,
            repo,
            issue_number: prNumber,
            per_page: 100,
          })
        : (
            await octokit.rest.issues.listComments({
              owner,
              repo,
              issue_number: prNumber,
              per_page: 100,
            })
          ).data;

    // Prefer the explicit marker; fall back to the legacy header substring so
    // PRs that received a comment before this change still get updated in place
    // instead of duplicated.
    const markerMatch = comments.find((c) => c.body?.includes(SUMMARY_MARKER));
    if (markerMatch) return markerMatch.id;

    const legacyMatch = comments.find((c) => c.body?.includes(LEGACY_SUMMARY_HEADER));
    return legacyMatch?.id ?? null;
  } catch (error) {
    core.warning(`Failed to find existing comment: ${String(error)}`);
    return null;
  }
}

export async function createOrUpdatePRComment(
  octokit: ReturnType<typeof github.getOctokit>,
  data: PRCommentData,
): Promise<void> {
  const { owner, repo, prNumber, results, options } = data;

  try {
    try {
      await octokit.rest.repos.get({ owner, repo });
    } catch (error: unknown) {
      const ghError = error as { status?: number };
      if (ghError.status === 403) {
        core.error(
          '❌ Permission denied: Cannot access repository. Make sure the GitHub token has "pull-requests: write" permission.',
        );
        return;
      }
      throw error;
    }

    const context: RepositoryContext = {
      owner,
      repo,
      prNumber,
      ref: github.context.ref,
      baseUrl: new URL(github.context.serverUrl),
      runId: github.context.runId,
    };
    const body = generateCommentBody(results, options, data.eventType, context);
    const existingCommentId = await findExistingComment(octokit, owner, repo, prNumber);

    if (existingCommentId) {
      await octokit.rest.issues.updateComment({
        owner,
        repo,
        comment_id: existingCommentId,
        body,
      });
      core.info(`✅ Updated existing comment on PR #${prNumber.toString()}`);
    } else {
      await octokit.rest.issues.createComment({
        owner,
        repo,
        issue_number: prNumber,
        body,
      });
      core.info(`✅ Created new comment on PR #${prNumber.toString()}`);
    }
  } catch (error: unknown) {
    const ghError = handleGitHubError(error, "Create/update PR comment");
    if (ghError.status === 403) {
      core.error("❌ Permission denied: Cannot create or update comments on pull requests.");
      core.error('Please ensure the GitHub token has "pull-requests: write" permission.');
    } else if (ghError.status === 404) {
      core.error("❌ Pull request not found. Make sure the PR exists and is accessible.");
    } else {
      logError(ghError, "Failed to create/update PR comment");
    }
  }
}

async function postReviewComments(
  octokit: ReturnType<typeof github.getOctokit>,
  owner: string,
  repo: string,
  prNumber: number,
  commitId: string,
  comments: ReviewCommentPayload[],
): Promise<void> {
  if (comments.length === 0) return;

  try {
    await octokit.rest.pulls.createReview({
      owner,
      repo,
      pull_number: prNumber,
      commit_id: commitId,
      event: "COMMENT",
      comments,
    });
    core.info(`✅ Created PR review with ${comments.length.toString()} comments`);
  } catch (error: unknown) {
    const ghError = handleGitHubError(error, "Create PR review comments");
    if (ghError.status === 403) {
      core.error("❌ Permission denied: Cannot create PR review comments.");
      core.error('Please ensure the GitHub token has "pull-requests: write" permission.');
      return;
    }
    core.warning(
      `Bulk review creation failed (${ghError.status?.toString() ?? "unknown"}). Posting comments individually.`,
    );
    let posted = 0;
    for (const comment of comments) {
      try {
        await octokit.rest.pulls.createReviewComment({
          owner,
          repo,
          pull_number: prNumber,
          commit_id: commitId,
          path: comment.path,
          line: comment.line,
          side: comment.side,
          body: comment.body,
        });
        posted++;
      } catch (commentError) {
        core.warning(
          `Failed to create review comment for ${comment.path}:${comment.line.toString()}: ${String(commentError)}`,
        );
      }
    }
    core.info(
      `✅ Posted ${posted.toString()}/${comments.length.toString()} review comments individually`,
    );
  }
}

async function applyUpdates(
  octokit: ReturnType<typeof github.getOctokit>,
  owner: string,
  repo: string,
  updates: { id: number; body: string }[],
): Promise<number> {
  let updated = 0;
  for (const { id, body } of updates) {
    try {
      await octokit.rest.pulls.updateReviewComment({
        owner,
        repo,
        comment_id: id,
        body,
      });
      updated++;
    } catch (error) {
      core.warning(`Failed to update review comment ${id.toString()}: ${String(error)}`);
    }
  }
  return updated;
}

async function applyDeletes(
  octokit: ReturnType<typeof github.getOctokit>,
  owner: string,
  repo: string,
  ids: number[],
): Promise<number> {
  let deleted = 0;
  for (const id of ids) {
    try {
      await octokit.rest.pulls.deleteReviewComment({
        owner,
        repo,
        comment_id: id,
      });
      deleted++;
    } catch (error) {
      core.warning(`Failed to delete review comment ${id.toString()}: ${String(error)}`);
    }
  }
  return deleted;
}

export async function createPRReviewComments(
  octokit: ReturnType<typeof github.getOctokit>,
  data: PRCommentData,
): Promise<void> {
  const { owner, repo, prNumber, results } = data;
  const desired = buildReviewComments(results);
  const existing = await listAllReviewComments(octokit, owner, repo, prNumber);
  const { toCreate, toUpdate, toDelete } = reconcileReviewComments(existing, desired);

  if (toCreate.length === 0 && toUpdate.length === 0 && toDelete.length === 0) {
    core.info("No review-comment changes needed; current state matches existing comments.");
    return;
  }

  core.info(
    `Reconciling review comments: ${toCreate.length.toString()} new, ${toUpdate.length.toString()} updated, ${toDelete.length.toString()} deleted (existing: ${existing.length.toString()}, desired: ${desired.length.toString()}).`,
  );

  if (toCreate.length > 0) {
    const payload = github.context.payload as { pull_request?: { head?: { sha?: string } } };
    const commitId = payload.pull_request?.head?.sha;
    if (!commitId) {
      core.warning("Unable to determine PR head SHA for new review comments; skipping creates.");
    } else {
      await postReviewComments(octokit, owner, repo, prNumber, commitId, toCreate);
    }
  }

  if (toUpdate.length > 0) {
    const updated = await applyUpdates(octokit, owner, repo, toUpdate);
    core.info(`✅ Updated ${updated.toString()}/${toUpdate.length.toString()} review comments`);
  }

  if (toDelete.length > 0) {
    const deleted = await applyDeletes(octokit, owner, repo, toDelete);
    core.info(
      `✅ Deleted ${deleted.toString()}/${toDelete.length.toString()} stale review comments`,
    );
  }
}

export function isPullRequestEvent(): boolean {
  return github.context.eventName === "pull_request";
}

export function getPRNumber(): number | null {
  if (github.context.eventName === "pull_request") {
    return github.context.issue.number;
  }
  return null;
}
