/**
 * PR Comment service for managing comments on pull requests
 */

import * as core from "@actions/core";
import * as github from "@actions/github";
import { AnalysisIssue, AnalysisOptions, AnalysisResult } from "../types/index.js";
import { generateAnalysisContent, RepositoryContext } from "../utils/markdown-utils.js";
import { capitalizeLabel, truncateText, wrapInlineCode } from "../utils/string-utils.js";
import { handleGitHubError, logError } from "../utils/error-utils.js";

export interface PRCommentData {
  owner: string;
  repo: string;
  prNumber: number;
  results: AnalysisResult[];
  options: AnalysisOptions;
  eventType: string;
}

interface ReviewCommentPayload {
  path: string;
  line: number;
  side: "RIGHT";
  body: string;
}

const MAX_REVIEW_COMMENTS = 50;
const MAX_ISSUES_PER_COMMENT = 5;
const MAX_ORIGINAL_LENGTH = 160;

function generateCommentBody(
  results: AnalysisResult[],
  options: AnalysisOptions,
  eventType: string,
  context: RepositoryContext,
): string {
  const header = `## 🔍 Markup AI Analysis Results

This comment was automatically generated by the Markup AI GitHub Action for **${eventType}** event.`;

  return generateAnalysisContent(results, options, header, eventType, context);
}

function pickSuggestion(issue: AnalysisIssue["issue"]): string | null {
  if (issue.suggestion && issue.suggestion.length > 0) return issue.suggestion;
  if (issue.suggestions && issue.suggestions.length > 0) return issue.suggestions[0];
  return null;
}

function applyInlineSuggestion(
  issue: AnalysisIssue["issue"],
  lineText: string,
  column: number,
): string | null {
  const suggestion = pickSuggestion(issue);
  const original = issue.position?.text ?? issue.context_surface ?? "";
  if (!suggestion || !original || !lineText) return null;

  const columnIndex = Math.min(Math.max(column, 0), lineText.length);
  const after = lineText.slice(columnIndex);
  if (after.startsWith(original)) {
    return `${lineText.slice(0, columnIndex)}${suggestion}${after.slice(original.length)}`;
  }

  const fallbackIndex = lineText.indexOf(original);
  if (fallbackIndex >= 0) {
    return `${lineText.slice(0, fallbackIndex)}${suggestion}${lineText.slice(
      fallbackIndex + original.length,
    )}`;
  }
  return null;
}

function buildReviewCommentBody(issues: AnalysisIssue[]): string {
  const lines = issues.slice(0, MAX_ISSUES_PER_COMMENT).map(({ issue, lineText, column }) => {
    const category = capitalizeLabel(issue.category);
    const guideline = issue.guideline_name ? capitalizeLabel(issue.guideline_name) : "";
    const heading = guideline ? `${category} / ${guideline}` : category;
    const original = truncateText(
      issue.position?.text ?? issue.context_surface ?? "",
      MAX_ORIGINAL_LENGTH,
    );
    const suggestion = pickSuggestion(issue);
    const explanationLine = issue.explanation ? `\n*Explanation: ${issue.explanation}*` : "";
    const inline = applyInlineSuggestion(issue, lineText, column);

    let suggestionBlock = "";
    if (inline) {
      suggestionBlock = `${explanationLine}\n\`\`\`suggestion\n${inline}\n\`\`\``;
    } else if (suggestion) {
      suggestionBlock = `${explanationLine}\nSuggestion: ${wrapInlineCode(truncateText(suggestion, MAX_ORIGINAL_LENGTH))}`;
    } else if (issue.explanation) {
      suggestionBlock = explanationLine;
    }

    const severity = ` (Severity: ${capitalizeLabel(issue.severity)})`;
    return `- **${heading}${severity}**: ${wrapInlineCode(original || "(no excerpt)")}${suggestionBlock}`;
  });

  const moreCount = issues.length - lines.length;
  if (moreCount > 0) {
    lines.push(`- _${moreCount.toString()} more issue(s) on this line_`);
  }

  return `**Markup AI** detected issues:\n${lines.join("\n")}`;
}

function buildReviewComments(results: AnalysisResult[]): ReviewCommentPayload[] {
  const grouped = new Map<string, { path: string; line: number; issues: AnalysisIssue[] }>();

  for (const result of results) {
    for (const issue of result.issues) {
      if (!issue.line || issue.line <= 0) continue;
      const key = `${result.filePath}:${issue.line.toString()}`;
      const existing = grouped.get(key);
      if (existing) {
        existing.issues.push(issue);
      } else {
        grouped.set(key, { path: result.filePath, line: issue.line, issues: [issue] });
      }
    }
  }

  const comments: ReviewCommentPayload[] = [];
  for (const { path, line, issues } of grouped.values()) {
    if (comments.length >= MAX_REVIEW_COMMENTS) break;
    comments.push({
      path,
      line,
      side: "RIGHT",
      body: buildReviewCommentBody(issues),
    });
  }

  return comments;
}

function filterExistingReviewComments(
  reviewComments: ReviewCommentPayload[],
  existingKeys: Set<string>,
): ReviewCommentPayload[] {
  const filtered: ReviewCommentPayload[] = [];
  for (const comment of reviewComments) {
    const key = `${comment.path}:${comment.line.toString()}:${comment.body}`;
    if (existingKeys.has(key)) {
      core.info(`Skipping existing review comment for ${comment.path}:${comment.line.toString()}`);
      continue;
    }
    filtered.push(comment);
  }
  return filtered;
}

async function getExistingReviewCommentKeys(
  octokit: ReturnType<typeof github.getOctokit>,
  owner: string,
  repo: string,
  prNumber: number,
): Promise<Set<string>> {
  try {
    const comments =
      typeof octokit.paginate === "function"
        ? await octokit.paginate(octokit.rest.pulls.listReviewComments, {
            owner,
            repo,
            pull_number: prNumber,
            per_page: 100,
          })
        : (
            await octokit.rest.pulls.listReviewComments({
              owner,
              repo,
              pull_number: prNumber,
              per_page: 100,
            })
          ).data;

    const keys = new Set<string>();
    for (const comment of comments) {
      if (comment.path && typeof comment.line === "number") {
        const resolved = (comment as { resolved?: boolean }).resolved;
        if (resolved === true) continue;
        keys.add(`${comment.path}:${comment.line.toString()}:${comment.body}`);
      }
    }
    return keys;
  } catch (error) {
    core.warning(`Failed to load existing review comments: ${String(error)}`);
    return new Set<string>();
  }
}

async function findExistingComment(
  octokit: ReturnType<typeof github.getOctokit>,
  owner: string,
  repo: string,
  prNumber: number,
): Promise<number | null> {
  try {
    const response = await octokit.rest.issues.listComments({
      owner,
      repo,
      issue_number: prNumber,
    });

    const comment = response.data.find((c) => c.body?.includes("Markup AI Analysis Results"));
    return comment?.id ?? null;
  } catch (error) {
    core.warning(`Failed to find existing comment: ${String(error)}`);
    return null;
  }
}

export async function createOrUpdatePRComment(
  octokit: ReturnType<typeof github.getOctokit>,
  data: PRCommentData,
): Promise<void> {
  const { owner, repo, prNumber, results, options } = data;

  try {
    try {
      await octokit.rest.repos.get({ owner, repo });
    } catch (error: unknown) {
      const ghError = error as { status?: number };
      if (ghError.status === 403) {
        core.error(
          '❌ Permission denied: Cannot access repository. Make sure the GitHub token has "pull-requests: write" permission.',
        );
        return;
      }
      throw error;
    }

    const context: RepositoryContext = {
      owner,
      repo,
      prNumber,
      ref: github.context.ref,
      baseUrl: new URL(github.context.serverUrl),
      runId: github.context.runId,
    };
    const body = generateCommentBody(results, options, data.eventType, context);
    const existingCommentId = await findExistingComment(octokit, owner, repo, prNumber);

    if (existingCommentId) {
      await octokit.rest.issues.updateComment({
        owner,
        repo,
        comment_id: existingCommentId,
        body,
      });
      core.info(`✅ Updated existing comment on PR #${prNumber.toString()}`);
    } else {
      await octokit.rest.issues.createComment({
        owner,
        repo,
        issue_number: prNumber,
        body,
      });
      core.info(`✅ Created new comment on PR #${prNumber.toString()}`);
    }
  } catch (error: unknown) {
    const ghError = handleGitHubError(error, "Create/update PR comment");
    if (ghError.status === 403) {
      core.error("❌ Permission denied: Cannot create or update comments on pull requests.");
      core.error('Please ensure the GitHub token has "pull-requests: write" permission.');
    } else if (ghError.status === 404) {
      core.error("❌ Pull request not found. Make sure the PR exists and is accessible.");
    } else {
      logError(ghError, "Failed to create/update PR comment");
    }
  }
}

export async function createPRReviewComments(
  octokit: ReturnType<typeof github.getOctokit>,
  data: PRCommentData,
): Promise<void> {
  const { owner, repo, prNumber, results } = data;
  const reviewComments = buildReviewComments(results);

  if (reviewComments.length === 0) {
    core.info("No review comments to create.");
    return;
  }

  const existingKeys = await getExistingReviewCommentKeys(octokit, owner, repo, prNumber);
  const filteredComments = filterExistingReviewComments(reviewComments, existingKeys);

  if (filteredComments.length === 0) {
    core.info(
      "No new review comments to create: all detected issues already have unresolved review comments.",
    );
    return;
  }

  const payload = github.context.payload as { pull_request?: { head?: { sha?: string } } };
  const commitId = payload.pull_request?.head?.sha;
  if (!commitId) {
    core.warning("Unable to determine PR head SHA for review comments.");
    return;
  }

  try {
    await octokit.rest.pulls.createReview({
      owner,
      repo,
      pull_number: prNumber,
      commit_id: commitId,
      event: "COMMENT",
      comments: filteredComments,
    });
    core.info(`✅ Created PR review with ${filteredComments.length.toString()} comments`);
  } catch (error: unknown) {
    const ghError = handleGitHubError(error, "Create PR review comments");
    if (ghError.status === 403) {
      core.error("❌ Permission denied: Cannot create PR review comments.");
      core.error('Please ensure the GitHub token has "pull-requests: write" permission.');
      return;
    }
    // GitHub's bulk createReview can fail (422 for off-diff lines, 500 when
    // overstuffed). Fall back to posting comments one at a time so usable ones
    // still land.
    core.warning(
      `Bulk review creation failed (${ghError.status?.toString() ?? "unknown"}). Posting comments individually.`,
    );
    let posted = 0;
    for (const comment of filteredComments) {
      try {
        await octokit.rest.pulls.createReviewComment({
          owner,
          repo,
          pull_number: prNumber,
          commit_id: commitId,
          path: comment.path,
          line: comment.line,
          side: comment.side,
          body: comment.body,
        });
        posted++;
      } catch (commentError) {
        core.warning(
          `Failed to create review comment for ${comment.path}:${comment.line.toString()}: ${String(commentError)}`,
        );
      }
    }
    core.info(
      `✅ Posted ${posted.toString()}/${filteredComments.length.toString()} review comments individually`,
    );
  }
}

export function isPullRequestEvent(): boolean {
  return github.context.eventName === "pull_request";
}

export function getPRNumber(): number | null {
  if (github.context.eventName === "pull_request") {
    return github.context.issue.number;
  }
  return null;
}
